repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.4.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-json
    - id: pretty-format-json
      args: ['--autofix','--indent=2','--no-ensure-ascii','--no-sort-keys']
    - id: check-yaml
    - id: check-xml
    - id: check-toml
    - id: trailing-whitespace
      args: ['--markdown-linebreak-ext=md']
    - id: mixed-line-ending
      args: ['--fix=lf']
      description: Forces to replace line ending by the UNIX 'lf' character.
    - id: end-of-file-fixer
      description: Makes sure files end in a newline and only a newline.
    - id: check-merge-conflict
      description: Check for files that contain merge conflict strings.
    - id: check-shebang-scripts-are-executable
    - id: check-added-large-files
      args: ['--maxkb=200']

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
    - id: terraform-validate
    - id: terraform-fmt

- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.16.0
  hooks:
    - id: terraform-docs-go
      args: ["."]

# pre-commit.ci configuration
ci:
  autofix_commit_msg: "style: auto fixes from pre-commit.ci"
  skip: [terraform-validate,terraform-fmt]
