name: ci

on:
  push:
    pull_request:

env:
  GO_VERSION: "1.18.3"
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2

      - uses: actions/setup-python@v3

      - uses: pre-commit/action@v3.0.0
